### ISSUE TITLE
Dead link for Ackley's paper.

### ISSUE THREAD

**Issue by caranha** [kaBeech/tensort#109]
The link for Ackley's "Beyond Efficiency" paper seems to be 404'ing

https://www.cs.unm.edu/~ackley/be-201301131528.pdf

**Comment by kaBeech** [comment]
@caranha Huh, it sure is. Thanks for letting me know!

I updated the links to point to archived copies. Could you please verify whether [this link](https://web.archive.org/web/20240809143400/https://www.cs.unm.edu/~ackley/be-201301131528.pdf) works for you?

**Comment by caranha** [comment]
Yes, this works! Wonderful idea for a project, btw!

**Comment by kaBeech** [comment]
Thank you very much!
